HYDRA-1207 - fix and re-enable case testSceneBrowser
Autodesk/maya-hydra pull request #182
Opened 2024-10-02 20:16 UTC by lilike-adsk

Adjust test code in sceneBrowser to make the case happy on SdfPathVector value to compensate the change in USD: https://github.com/PixarAnimationStudios/OpenUSD/commit/1d19b1dbdd0daf12247f5a1cb4b858c444e3e4fa#diff-8c7415891d45a3810ea025ac58c7e025043412150b628560c12a1b8fdbe1f830R57

2024-10-02 20:17 UTC, lilike-adsk commented
@ppt-adsk @lanierd-adsk

2024-10-02 20:20 UTC, ppt-adsk commented on lib/adskHydraSceneBrowser/test/adskHydraSceneBrowserTestFixture.cpp
> +    if (value.IsHolding<pxr::SdfPathVector>()) {
What about other vector types?  E.g. vectors of Plain Old Data (POD) types, like integers, floats?

2024-10-02 21:50 UTC, lilike-adsk commented on lib/adskHydraSceneBrowser/test/adskHydraSceneBrowserTestFixture.cpp
> +    if (value.IsHolding<pxr::SdfPathVector>()) {
For other types, it still keeps unchanged, the Qt widget still present the content in the way of `buffer << _value;`
It's same as what we fetch from dataSource here: `valueStream << value`,

2024-10-02 21:53 UTC, debloip-adsk requested changes

2024-10-02 21:53 UTC, debloip-adsk commented on lib/adskHydraSceneBrowser/test/adskHydraSceneBrowserTestFixture.cpp
> +    if (value.IsHolding<pxr::SdfPathVector>()) {
Yeah this code's goal is to test that the UI displays the intended result, so we just mimic the behaviour from the actual scene browser code, seen in the [link Keli put in the description of this PR](https://github.com/PixarAnimationStudios/OpenUSD/commit/1d19b1dbdd0daf12247f5a1cb4b858c444e3e4fa#diff-8c7415891d45a3810ea025ac58c7e025043412150b628560c12a1b8fdbe1f830R57). I would definitely add this link in a comment though. Otherwise looks good to me.

2024-10-03 13:10 UTC, ppt-adsk approved these changes

2024-10-03 13:31 UTC, debloip-adsk approved these changes

2024-10-03 13:40 UTC, merged