[WIP] HYDRA-747 : Filtering scene index example can have prims get unfiltered at the wrong location
Autodesk/maya-hydra pull request #42
Opened 2024-01-18 16:52 UTC by debloip-adsk

The issue in this case was that when the prim was added, it was initially pruned out. Then, when changing the number of vertices so that it is no longer pruned, only a PrimsDirtied notification was sent on the mesh. This means that downstream scene indices were never made aware of the prim's xform data source, or of the prim's addition.

This issue is more general in that pruning scene indices such as this one need to be aware of which prims are initially pruned out, so that they can provide a coherent scene view to downstream scene indices. The current solution to this issue is to traverse the scene in the scene index ctor and store which prims are initially pruned, and update this set in PrimsAdded and PrimsRemoved. That way, in PrimsDirtied, we can always correctly determine for a given prim whether to forward the dirty notification, or if we should send a PrimsAdded/PrimsRemoved if a prim's pruning status changed.

2024-01-31 19:53 UTC, debloip-adsk commented
FYI @ppt-adsk @lilike-adsk @roopavr-adsk @vlasovi

2024-02-01 13:48 UTC, lanierd-adsk requested changes
Can you please add a unit test for the different cases ? So we are sure it works and we don't break it any more.

2024-02-01 13:48 UTC, lanierd-adsk commented on lib/flowViewport/API/samples/fvpFilteringSceneIndexExample.cpp
> +    SdfPathVector childPaths = _GetInputSceneIndex()->GetChildPrimPaths(primPath);
Can you please add a comment here to say you're automatically hiding the children of an hidden prim ? It will help in case of debugging if required one day...  Thanks !

2024-02-01 21:53 UTC, debloip-adsk commented on lib/flowViewport/API/samples/fvpFilteringSceneIndexExample.cpp
> +    SdfPathVector childPaths = _GetInputSceneIndex()->GetChildPrimPaths(primPath);
Done!

2024-02-01 22:10 UTC, debloip-adsk commented
> Can you please add a unit test for the different cases ? So we are sure it works and we don't break it any more.

I've added a check for the renderer switching case which is the original bug that started this, as well as for filtering and unfiltering in similar cases. However, I can't really test that child prims of a filtered prim are also filtered out, because from what I see our mesh prims are always leaf prims, so they never have children.

2024-02-02 09:49 UTC, lanierd-adsk approved these changes

2024-02-02 14:25 UTC, ppt-adsk commented
> > Can you please add a unit test for the different cases ? So we are sure it works and we don't break it any more.
> 
> I've added a check for the renderer switching case which is the original bug that started this, as well as for filtering and unfiltering in similar cases. However, I can't really test that child prims of a filtered prim are also filtered out, because from what I see our mesh prims are always leaf prims, so they never have children.

This will always be the case for Maya, since shape nodes must be leaves, and is the rule for well-constructed USD scenes as well --- see
https://openusd.org/release/glossary.html#usdglossary-gprim

2024-02-02 20:05 UTC, merged