HYDRA-824 - add unit test for maya lights
Autodesk/maya-hydra pull request #52
Opened 2024-01-31 14:09 UTC by lilike-adsk

Modify the testDirectionalLights test to cover more cases for MAYA lights:
1.different lighting modes
2.shadow on/off

2024-01-31 14:11 UTC, lilike-adsk commented
FYI @debloip-adsk @roopavr-adsk @ppt-adsk @vlasovi

2024-02-01 13:30 UTC, lanierd-adsk requested changes

2024-02-01 13:30 UTC, lanierd-adsk commented on test/lib/mayaUsd/render/mayaToHydra/MayaLightsTest/flatLight.png
This image is exactly the same as with Shadows on. But I guess it's broken ? Is that the expected result ?

2024-02-01 13:30 UTC, lanierd-adsk commented on test/lib/mayaUsd/render/mayaToHydra/MayaLightsTest/flatLight.png
It is the same as nolight.png. I think there is a problem.

2024-02-01 13:30 UTC, lanierd-adsk commented on test/lib/mayaUsd/render/mayaToHydra/MayaLightsTest/noLight_shadowOn.png
If you have a scene with no light, I think it's not necessary to render an image without shadows. You could remove that test which is exactly the same image as the nolight.png

2024-02-01 13:30 UTC, lanierd-adsk commented on test/lib/mayaUsd/render/mayaToHydra/MayaLightsTest/pointLight_shadowOn.png
I don't see any difference visually between the pointLight.png file, is there any ?

2024-02-01 13:30 UTC, lanierd-adsk commented on test/lib/mayaUsd/render/mayaToHydra/MayaLightsTest/spotLight_shadowOn.png
Same here, no difference between this image and spotLight.png. Is that expected ?

2024-02-01 13:30 UTC, lanierd-adsk commented on test/lib/mayaUsd/render/mayaToHydra/testMayaLights.py
> +class TesMayatLights(mtohUtils.MtohTestCase): #Subclassing mtohUtils.MtohTestCase to be able to call self.assertSnapshotClose
The "t" from test has been moved after Maya in the class name. :-)  Can you please fix it ? Thanks.

2024-02-01 13:30 UTC, lanierd-adsk commented on test/lib/mayaUsd/render/mayaToHydra/testMayaLights.py
> +        #Do a view fit --Test removed as on Linux the fit doesn't produce the same result as on Windows and OSX.
Can you please remove that commented code which I did in a previous PR, it's not required to keep it. Thanks.

2024-02-01 13:41 UTC, lilike-adsk commented on test/lib/mayaUsd/render/mayaToHydra/MayaLightsTest/flatLight.png
flatLight won't create shadows, that's expected.
flatLight results (constant shading) should be different vs. noLight, this seems to be broken or never works.

We can leave the images here, and rebaseline when the issue is fixed.

2024-02-01 13:42 UTC, lilike-adsk commented on test/lib/mayaUsd/render/mayaToHydra/MayaLightsTest/noLight_shadowOn.png
I'm fine to remove that case.

2024-02-01 13:45 UTC, lilike-adsk commented on test/lib/mayaUsd/render/mayaToHydra/MayaLightsTest/pointLight_shadowOn.png
This seems to be broken or never works.

2024-02-01 13:50 UTC, lanierd-adsk commented on test/lib/mayaUsd/render/mayaToHydra/MayaLightsTest/flatLight.png
I would prefer removing the wrong images of what is not working and comment the code producing the images in this test and add a JIRA so we fix/support it later. Thanks !

2024-02-01 13:50 UTC, lanierd-adsk commented on test/lib/mayaUsd/render/mayaToHydra/MayaLightsTest/pointLight_shadowOn.png
I would prefer removing the wrong images of what is not working and comment the code producing the images in this test and add a JIRA so we fix/support it later. Thanks !

2024-02-02 09:23 UTC, lanierd-adsk approved these changes

2024-02-02 13:59 UTC, merged