HYDRA-813 - add test for usd lights
Autodesk/maya-hydra pull request #53
Opened 2024-01-31 14:21 UTC by lilike-adsk

Add test for usd lights to cover:
1.all lighting modes
2.shadow on/off

Note: some test code are commented out due to some features are not supported yet.

2024-01-31 14:27 UTC, lilike-adsk commented
FYI @debloip-adsk @roopavr-adsk @ppt-adsk @vlasovi

2024-02-01 13:36 UTC, lanierd-adsk requested changes

2024-02-01 13:36 UTC, lanierd-adsk commented on test/lib/mayaUsd/render/mayaToHydra/testUSDLights.py
> +        #TODO: Enable code below when those lighting modes are supported by usd lights
If not already done, can you please log a JIRA for this ?

2024-02-01 13:36 UTC, lanierd-adsk commented on test/lib/mayaUsd/render/mayaToHydra/testUSDLights.py
> +        #Do a view fit --Test removed as on Linux the fit doesn't produce the same result as on Windows and OSX.
Please remove the comment from a previous PR. Thanks.

2024-02-01 13:36 UTC, lanierd-adsk commented on test/lib/mayaUsd/render/mayaToHydra/testUSDLights.py
> +        cmds.refresh()
I think this refresh is not required since you do it already line 82.

2024-02-01 13:36 UTC, lanierd-adsk commented on test/lib/mayaUsd/render/mayaToHydra/USDLightsTest/allLights.png
Is the ocean look on purpose and usefull to this test ? I think the ocean look and the "scratches" in the top of the images in an orange-ish color may be problematic. Unless they bring something usefull for this test, I would remove them. It's likely the sky.hdr file that contains these.

2024-02-01 13:59 UTC, lilike-adsk commented on test/lib/mayaUsd/render/mayaToHydra/USDLightsTest/allLights.png
that's required for validating usd dome light.

2024-02-01 14:25 UTC, lanierd-adsk commented on test/lib/mayaUsd/render/mayaToHydra/USDLightsTest/allLights.png
ok, thanks.

2024-02-02 09:52 UTC, lanierd-adsk approved these changes, later dismissed

2024-02-05 10:27 UTC, lanierd-adsk approved these changes

2024-02-05 13:08 UTC, merged