Update build.py to support MtoA artifactory download
Autodesk/maya-hydra pull request #69
Opened 2024-02-13 16:28 UTC by roopavr-adsk

2024-02-13 20:28 UTC, seando-adsk requested changes

2024-02-13 20:28 UTC, seando-adsk commented on build.py
> +                             .format(mayaUsdLocation=context.mayaUsdLocation.replace("\\","/")))
You should not need the replace here.

2024-02-13 20:28 UTC, seando-adsk commented on build.py
> +                                if args.mtoa_location else None)
Add the replace here (like it is for mayaUsdLocation) above. Then these are sent to the BuildAndInstall and will have the / so no replace needed there.

2024-02-14 16:25 UTC, roopavr-adsk commented
Closing this PR as I cannot add another file to the PR. This PR was created while editing build.py in place on GitHub.

https://github.com/Autodesk/maya-hydra/pull/71

2024-02-14 16:25 UTC, closed without merging