HYDRA-762 - Investigate why the tumbling performance of USD scene is slower than corresponding Maya Scene under Hydra Storm
Autodesk/maya-hydra pull request #91
Opened 2024-03-01 15:06 UTC by vlasovi

Fixing double-rendering of USD prims + autotest

2024-03-01 15:07 UTC, vlasovi commented
FYI : @lilike-adsk @roopavr-adsk @debloip-adsk @lanierd-adsk

2024-03-01 15:44 UTC, lilike-adsk commented
Nice catch! @vlasovi, I assume now, we can get similar fps on USD scene as corresponding Maya scene , right?

2024-03-01 20:16 UTC, vlasovi commented
> Nice catch! @vlasovi, I assume now, we can get similar fps on USD scene as corresponding Maya scene , right?

Yes

2024-03-04 19:14 UTC, ppt-adsk requested changes
Looks good to me, though I wouldn't tie the test to the scene browser.

2024-03-04 19:14 UTC, ppt-adsk commented on lib/adskHydraSceneBrowser/test/adskHydraSceneBrowserTestFixture.cpp
> +    QTreeWidgetItemIterator itPrimsTreeWidget = GetIteratorForTree(_primHierarchyWidget);
Thanks for the test, looks good, but it feels out of place to tie it to the scene browser.  I asked @debloip-adsk and he agreed with me, saying that 
> with APIs like GetChildPrimPaths, GetPrim, Get methods for container data sources (or GetElement for vector data sources) + casts, and GetValue/GetTypeValue methods on data sources, the whole scene index scene hierarchy can be inspected.

Here's an example you might like:
https://github.com/Autodesk/maya-hydra/blob/dev/test/lib/mayaUsd/render/mayaToHydra/cpp/testPrimInstancing.cpp
It shouldn't change the logic of the test.

2024-03-06 18:21 UTC, ppt-adsk approved these changes
Great work, thanks for the test!

2024-03-06 20:52 UTC, merged